### ISSUE TITLE
map—camera should not respond to requests to zoom to the currently selected node

### ISSUE THREAD

**Issue by phelow** [pcioni/CISL#11]
could have an audio response (negative) to indicate that the input was received, but unnecessary.

**Comment by ludimation** [comment]
Likely in ViewModeController.cs

**Comment by ludimation** [comment]
Fixed with 410ff82.

(Still does a short bump motion, but that's acceptable as it gives feedback that you're already on the current node.)

**Comment by ludimation** [comment]
Should look at again, but with much lower priority—has undesired effects when spamming nodes on long transitions.

**Comment by ludimation** [comment]
Fixed with c9b14f0.
