### ISSUE TITLE
map—camera depth should not be reset on a zoom request

### ISSUE THREAD

**Issue by phelow** [pcioni/CISL#12]
if a zoom change is already in progress, the camera should interpolate from current zoom.

**Comment by ludimation** [comment]
Likely in ViewModeController.cs

**Comment by ludimation** [comment]
I believe Craig may have fixed this with e54e2ec. Need to regress and see if it's working.

**Comment by ludimation** [comment]
This still has some strange behavior. I'll take a look at this after some of the other higher-priority bugs.

**Comment by ludimation** [comment]
Lowering priority since it's something that shouldn't be an issue unless spamming node presses.

**Comment by ludimation** [comment]
Fixed with c9b14f0.
