### ISSUE TITLE
timeline—label placement for legibility

### ISSUE THREAD

**Issue by phelow** [pcioni/CISL#22]
This is the second highest priority bug right now.

[ todo ]
 * resize group collider
     * width of widest nameTag
     * height of (n) nameTags * their height + padding
 * place collider to encompass the bounds of the group
 * have colliders avoid the mouse position (so labels don't appear over currently moused-over node)
 * automatically switch labels from right to left based on collisions & put tethers on appropriate side

[ desired behavior ]
 * labels should not overlap each other—overlapping labels should be clustered
 * labels should try to not overlap any nodes either

**Comment by ludimation** [comment]
[ done ] — 5761e4c
* left-align text within labels
* auto-extend label BG to fit text

**Comment by ludimation** [comment]
[ done ]
 * labels move appropriately when zooming in / out on the timeline
 * place labels to the right of the group collider
 * re-check for collisions

**Comment by ludimation** [comment]
[ done ] — 2e8e983
 * in-focus node label target updated on initialize

**Comment by ludimation** [comment]
Fixed with 158ca62.

**Comment by ludimation** [comment]
William, I was able to fix this for now, so please focus on the mapping from here. Thanks!
